# Generated by Django 3.2.11 on 2022-04-12 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bc_connect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('param', models.CharField(max_length=250)),
                ('post', models.CharField(max_length=250)),
                ('contant', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bc_connect.tenantapi')),
            ],
        ),
    ]
