# Generated by Django 3.2.11 on 2022-04-12 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bc_connect', '0002_apitraffic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apitraffic',
            old_name='contant',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='apitraffic',
            old_name='post',
            new_name='method',
        ),
        migrations.RenameField(
            model_name='apitraffic',
            old_name='type',
            new_name='response',
        ),
    ]
