# Generated by Django 3.2.11 on 2022-04-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_connect', '0003_auto_20220412_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitraffic',
            name='view',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
