# Generated by Django 3.2.11 on 2022-04-13 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bc_connect', '0006_alter_apitraffic_api'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apitraffic',
            name='path',
        ),
    ]
