# Generated by Django 3.2.11 on 2022-04-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_connect', '0007_remove_apitraffic_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitraffic',
            name='api',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='apitraffic',
            name='method',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='apitraffic',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apitraffic',
            name='view',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
