# Generated by Django 3.2.11 on 2022-06-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_connect', '0009_auto_20220425_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='app_type',
            field=models.CharField(choices=[('POS', 'POS'), ('Customer Portal', 'Customer Portal'), ('Item Consuption', 'Item Consuption')], default='', max_length=250),
            preserve_default=False,
        ),
    ]
