# Generated by Django 3.2.11 on 2022-06-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_connect', '0010_tenant_app_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='authenticationEmail',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='licenseType',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='state',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='password',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='username',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
