# Generated by Django 3.2.11 on 2022-08-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_connect', '0012_auto_20220823_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='key',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='localkey',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='scope',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
