# Generated by Django 3.2.11 on 2022-09-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_connect', '0013_auto_20220825_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='token',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
