# Generated by Django 3.2.11 on 2022-04-12 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('tenant_id', models.CharField(max_length=250)),
                ('company_id', models.CharField(max_length=250)),
                ('tenant_user', models.CharField(max_length=250)),
                ('key', models.CharField(max_length=250)),
                ('localkey', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantTransection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_template_name', models.CharField(max_length=250)),
                ('journal_batch_name', models.CharField(max_length=250)),
                ('bin_code', models.CharField(max_length=250)),
                ('employee_id', models.CharField(max_length=250)),
                ('registering_date', models.DateField()),
                ('response', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adk_item_consumer.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('full_name', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adk_item_consumer.tenant')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenantTransectionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.CharField(max_length=250)),
                ('location_code', models.CharField(max_length=250)),
                ('item_no', models.CharField(max_length=250)),
                ('lot_no', models.CharField(max_length=250)),
                ('serial_no', models.CharField(max_length=250)),
                ('patient_no', models.CharField(max_length=250)),
                ('quantity', models.CharField(max_length=250)),
                ('response', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('transection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adk_item_consumer.tenanttransection')),
            ],
        ),
        migrations.CreateModel(
            name='TenantItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('reference_no', models.CharField(max_length=250)),
                ('system_modified_at', models.DateTimeField()),
                ('stationConsumption', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adk_item_consumer.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('baseurl', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adk_item_consumer.tenant')),
            ],
        ),
    ]
