# Generated by Django 3.2.11 on 2022-04-12 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bc_connect', '0001_initial'),
        ('adk_item_consumer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantapi',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tenantuser',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tenantuser',
            name='user',
        ),
        migrations.AlterField(
            model_name='tenantitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bc_connect.tenant'),
        ),
        migrations.AlterField(
            model_name='tenanttransection',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bc_connect.tenant'),
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.DeleteModel(
            name='TenantApi',
        ),
        migrations.DeleteModel(
            name='TenantUser',
        ),
    ]
